INSERT INTO SKILL_DETAILS (`skill_name`, `skill_status`) VALUES
('Python Programming', 'active'),
('Java Programming', 'active'),
('C Programming', 'active'),
('C++ Programming', 'active'),
('R Programming', 'active'),
('SQL Programming', 'active'),
('Data Analytics', 'active'),
('Data Science', 'active'),
('Data Engineering', 'active'),
('Data Visualization', 'active'),
('Machine Learning', 'active'),
('Deep Learning', 'active'),
('Natural Language Processing', 'active'),
('Computer Vision', 'active'),
('Big Data', 'active'),
('Business Process Management', 'active'),
('Business Process Improvement', 'active'),
('Business Process Re-engineering', 'active'),
('Business Process Automation', 'active'),
('Business Process Outsourcing', 'active'),
('Business Process Modelling', 'active'),
('Business Process Mapping', 'active'),
('Business Process Design', 'active'),
('Business Process Redesign', 'active'),
('Business Process Transformation', 'active'),
('Business Process Integration', 'active'),
('Business Process Alignment', 'active'),
('Business Process Standardization', 'active'),
('Business Process Optimization', 'active'),
('Business Process Innovation', 'active'),
('Business Process Excellence', 'active'),
('Human Resource', 'active'),
('Finance', 'active'),
('Sales', 'active'),
('Information Technology', 'active'),
('Project Management', 'active'),
('Program Management', 'active'),
('Portfolio Management', 'active'),
('Product Management', 'active'),
('Account Management', 'active'),
('Accounting', 'active'),
('Administrative', 'active'),
('Advertising', 'active'),
('Agile', 'active');

INSERT INTO STAFF_DETAILS (`fname`, `lname`, `dept`, `email`, `phone`, `biz_address`, `sys_role`) VALUES
('AH GAO', 'TAN', 'FINANCE', 'tan_ah_gao@all-in-one.com.sg', '65 1234 5678', '1, Marina Boulevard, Singapore 018989', 'staff'),
('VINCENT REX', 'COLINS', 'HUMAN RESOURCE AND ADMIN', 'colins_vincent_rex@all-in-one.com.sg', '65 1334 5678', '1, Marina Boulevard, Singapore 018989', 'hr'),
('FAUD', 'NIZAM', 'SALES', 'faud_nizam@all-in-one.com.sg', '65 1434 5678', '1, Marina Boulevard, Singapore 018989', 'manager'),
('JOHN', 'DOE', 'IT', 'john_doe@all-in-one.com.sg', '65 1534 5678', '1, Marina Boulevard, Singapore 018989', 'inactive'),
('SAMUEL', 'TAN', 'IT', 'samuel_tan@all-in-one.com.sg', '65 1634 5678', '1, Marina Boulevard, Singapore 018989', 'staff'),
('JANE', 'GOH', 'IT', 'jane_goh@all-in-one.com.sg', '65 1734 5678', '1, Marina Boulevard, Singapore 018989', 'manager');


INSERT INTO ROLE_DETAILS (`role_name`, `role_description`, `role_status`) VALUES
('Data Scientist', 'Data Scientist', 'active'),
('Data Engineer', 'Data Engineer', 'active'),
('Data Analyst', 'Data Analyst', 'active'),
('Business Analyst', 'Business Analyst', 'active'),
('Business Process Analyst', 'Business Process Analyst', 'active'),
('Business Process Engineer', 'Business Process Engineer', 'active'),
('Business Process Consultant', 'Business Process Consultant', 'active'),
('Business Process Manager', 'Business Process Manager', 'active'),
('Business Process Architect', 'Business Process Architect', 'active'),
('Business Process Designer', 'Business Process Designer', 'active'),
('Business Process Developer', 'Business Process Developer', 'active'),
('Business Process Specialist', 'Business Process Specialist', 'active'),
('Business Process Expert', 'Business Process Expert', 'active'),
('Business Process Leader', 'Business Process Leader', 'active'),
('Business Process Owner', 'Business Process Owner', 'active'),
('Business Process Trainer', 'Business Process Trainer', 'active'),
('Business Process Auditor', 'Business Process Auditor', 'active'),
('Business Process Controller', 'Business Process Controller', 'active'),
('Agile Coach', 'Agile Coach', 'active'),
('Human Resource Manager', 'Human Resource Manager', 'active'),
('Finance Manager', 'Finance Manager', 'active'),
('Sales Manager', 'Sales Manager', 'active'),
('IT Manager', 'IT Manager', 'active'),
('Project Manager', 'Project Manager', 'active'),
('Program Manager', 'Program Manager', 'active'),
('Portfolio Manager', 'Portfolio Manager', 'active'),
('Product Manager', 'Product Manager', 'active'),
('Account Manager', 'Account Manager', 'active'),
('Account Executive', 'Account Executive', 'active'),
('Account Director', 'Account Director', 'active'),
('Account Specialist', 'Account Specialist', 'active'),
('Account Representative', 'Account Representative', 'active'),
('Account Coordinator', 'Account Coordinator', 'active'),
('Account Administrator', 'Account Administrator', 'active'),
('Account Assistant', 'Account Assistant', 'active'),
('Account Associate', 'Account Associate', 'active'),
('Account Analyst', 'Account Analyst', 'active'),
('Account Auditor', 'Account Auditor', 'active'),
('Account Collector', 'Account Collector', 'active'),
('Account Consultant', 'Account Consultant', 'active'),
('Account Controller', 'Account Controller', 'active'),
('Account Clerk', 'Account Clerk', 'active'),
('Account Director', 'Account Director', 'active'),
('Account Executive', 'Account Executive', 'active'),
('Account Manager', 'Account Manager', 'active'),
('Account Officer', 'Account Officer', 'active'),
('Account Representative', 'Account Representative', 'active'),
('Account Specialist', 'Account Specialist', 'active'),
('Account Supervisor', 'Account Supervisor', 'active'),
('Accountant', 'Accountant', 'active'),
('Accounting Assistant', 'Accounting Assistant', 'active'),
('Accounting Clerk', 'Accounting Clerk', 'active'),
('Accounting Consultant', 'Accounting Consultant', 'active'),
('Accounting Coordinator', 'Accounting Coordinator', 'active'),
('Accounting Director', 'Accounting Director', 'active'),
('Accounting Manager', 'Accounting Manager', 'active'),
('Accounting Officer', 'Accounting Officer', 'active'),
('Accounting Specialist', 'Accounting Specialist', 'active'),
('Accounting Supervisor', 'Accounting Supervisor', 'active'),
('Accounting Technician', 'Accounting Technician', 'active'),
('Accounts Payable Clerk', 'Accounts Payable Clerk', 'active'),
('Accounts Payable Manager', 'Accounts Payable Manager', 'active'),
('Accounts Payable Specialist', 'Accounts Payable Specialist', 'active'),
('Accounts Payable Supervisor', 'Accounts Payable Supervisor', 'active'),
('Accounts Receivable Clerk', 'Accounts Receivable Clerk', 'active'),
('Accounts Receivable Manager', 'Accounts Receivable Manager', 'active'),
('Accounts Receivable Specialist', 'Accounts Receivable Specialist', 'active'),
('Accounts Receivable Supervisor', 'Accounts Receivable Supervisor', 'active'),
('Administrative Assistant', 'Administrative Assistant', 'active'),
('Administrative Coordinator', 'Administrative Coordinator', 'active'),
('Administrative Director', 'Administrative Director', 'active'),
('Administrative Manager', 'Administrative Manager', 'active'),
('Administrative Officer', 'Administrative Officer', 'active'),
('Administrative Secretary', 'Administrative Secretary', 'active'),
('Administrative Specialist', 'Administrative Specialist', 'active'),
('Administrative Supervisor', 'Administrative Supervisor', 'active'),
('Administrative Support', 'Administrative Support', 'active'),
('Administrative Technician', 'Administrative Technician', 'active'),
('Administrator', 'Administrator', 'active'),
('Advertising Account Executive', 'Advertising Account Executive', 'active'),
('Advertising Account Manager', 'Advertising Account Manager', 'active'),
('Advertising Account Representative', 'Advertising Account Representative', 'active'),
('Advertising Account Specialist', 'Advertising Account Specialist', 'active'),
('Advertising Account Supervisor', 'Advertising Account Supervisor', 'active'),
('Advertising Assistant', 'Advertising Assistant', 'active'),
('Advertising Clerk', 'Advertising Clerk', 'active'),
('Advertising Coordinator', 'Advertising Coordinator', 'active'),
('Advertising Director', 'Advertising Director', 'active'),
('Advertising Manager', 'Advertising Manager', 'active'),
('Advertising Officer', 'Advertising Officer', 'active'),
('Advertising Representative', 'Advertising Representative', 'active'),
('Advertising Specialist', 'Advertising Specialist', 'active'),
('Advertising Supervisor', 'Advertising Supervisor', 'active'),
('Advertising Technician', 'Advertising Technician', 'active'),
('Agile Coach', 'Agile Coach', 'active'),
('Agile Project Manager', 'Agile Project Manager', 'active'),
('Agile Scrum Master', 'Agile Scrum Master', 'active'),
('Agile Team Lead', 'Agile Team Lead', 'active'),
('Agile Tester', 'Agile Tester', 'active'),
('Agile Trainer', 'Agile Trainer', 'active');

INSERT INTO STAFF_REPORTING_OFFICER (`staff_id`, `RO_id`) VALUES
(1, 3),
(2, 3),
(3, 3),
(4, 6),
(5, 6),
(6, 6);

INSERT INTO STAFF_ROLES (`staff_id`, `staff_role`, `role_type`, `sr_status`) VALUES
(1, 38, 'primary', 'active'),
(1, 67, 'secondary', 'active'),
(2, 20, 'primary', 'active'),
(2, 19, 'secondary', 'active'),
(3, 95, 'primary', 'active'),
(3, 27, 'secondary', 'active'),
(5, 2, 'primary', 'active'),
(5, 5, 'secondary', 'active'),
(6, 23, 'primary', 'active'),
(6, 24, 'secondary', 'active');

INSERT INTO STAFF_SKILLS (`staff_id`, `skill_id`, `ss_status`) VALUES
(1, 1, 'active'),
(1, 2, 'active'),
(2, 3, 'active'),
(1, 4, 'active'),
(2, 5, 'active'),
(1, 6, 'active'),
(3, 7, 'active'),
(4, 8, 'active'),
(3, 9, 'active'),
(5, 1, 'active'),
(5, 2, 'active'),
(5, 6, 'active'),
(5, 7, 'active'),
(5, 11, 'active'),
(5, 13, 'active'),
(6, 1, 'active'),
(6, 2, 'active'),
(6, 6, 'active'),
(6, 15, 'active'),
(6, 44, 'active'),
(2, 32, 'active');

INSERT INTO ROLE_SKILLS (`role_id`, `skill_id`) VALUES
(1, 1),
(1, 2),
(2, 3),
(1, 4),
(1, 5),
(2, 6),
(1, 7),
(3, 8),
(3, 9);

-- Insert 2 sample records into ROLE_LISTINGS table
INSERT INTO ROLE_LISTINGS (
    `role_listing_id`,
    `role_id`,
    `role_listing_desc`,
    `role_listing_source`,
    `role_listing_open`,
    `role_listing_close`,
    `role_listing_creator`,
    `role_listing_status`,
    `role_listing_updater`
)
VALUES
    (19458657, 1, 'Sample Role Listing 1', 3, '2023-10-01', '2023-10-10', 2, 'active', 2),
    (19458658, 3, 'Sample Role Listing 2', 3, '2023-11-01', '2023-11-10', 2, 'inactive', 2);

