name: Auto-Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Update branches
        run: |
          # Get the latest changes from the main branch
          git fetch origin main

          # Iterate through all branches in the repository (except main)
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v 'main'); do
            # Check out the branch
            git checkout $branch

            # Attempt to merge the latest changes from main
            if git merge origin/main --no-edit; then
              # If the merge is successful, push the updated branch
              git push origin $branch
            else
              # If there's a conflict, print a message and continue to the next branch
              echo "Conflict occurred in branch $branch. Skipping..."
            fi
          done
