name: Run Unit Test Python Flask Backend

on: 
  pull_request:
    branches: [ master, main ]
    paths: 
      - 'sbrp-frontend/api/**'
      - 'BE/unit-tests/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get-vercel-preview-url
        id: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.1.9
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_project_id: ${{ secrets.SBRP_PROJECT_ID }}
      - name: await-vercel-deployment
        uses: UnlyEd/github-action-await-vercel@v1
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: ${{ steps.vercel-preview-url.outputs.preview_url }}
          timeout: 600
      - name: install-required-packages
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install -r BE/requirements.txt
      - name: set-deployment-url-in-env
        run: |
          echo "VERCEL_DEPLOYMENT_URL=${{ steps.vercel-preview-url.outputs.preview_url }}" >> $GITHUB_ENV
      - name: run-unittest-python
        working-directory: ./BE/unit-tests
        env:
          BASE_URL: ${{ format('https://{0}', steps.vercel-preview-url.outputs.preview_url) }}
        run: |
          python3 -m unittest main_test.py
          
